# QA/QC for delivered administrative boundaries
The World Bank receives regular deliveries of official administrative boundaries. This script will process and evaluate these boundaries in several ways:

- Combine the two ID columns into a single, primary key  
  a. Check to ensure no duplicates in this new, primary key
- Combine ADM0 file with disputed areas shapefile 
- Create ocean mask 
- Within higher heirarchical level, evaluate name duplication
- Perform topological checks  
  a. Ensure no overlaps  
  b. Ensure no gaps  
  c. Ensure all admin1 and admin2 shapes are fully contained within their heirarchical parents

In [1]:
import sys, os
import requests
import json

import geopandas as gpd
import pandas as pd

from urllib.parse import quote
from shapely.geometry import Point, Polygon, box, shape
from GOSTrocks.misc import tPrint

sys.path.append("../src")

from wb_gad_helper import *

%load_ext autoreload
%autoreload 2

In [2]:
admin_folder = r'C:\WBG\Work\data\ADMIN\NEW_WB_BOUNDS'
old_admin_folder = r'C:\WBG\Work\data\ADMIN\OLD_WB_BOUNDS'
out_folder = r'C:\WBG\Work\data\ADMIN\QAQC'
final_folder = os.path.join(admin_folder, 'FOR_PUBLICATION')
if not os.path.exists(final_folder):
    os.makedirs(final_folder)
for file_format in ['gpkg', 'shp', 'geojson']:
    temp_folder = os.path.join(final_folder, file_format)
    if not os.path.exists(temp_folder):
        os.makedirs(temp_folder)

if not os.path.exists(out_folder):
    os.makedirs(out_folder)

admin0_file = os.path.join(admin_folder, 'WB_GAD_ADM0.shp')
adm0_disputes_file = os.path.join(admin_folder, 'WB_GAD_NDLSA.shp')
admin1_file = os.path.join(admin_folder, 'WB_GAD_ADM1.shp')
admin2_file = os.path.join(admin_folder, 'WB_GAD_ADM2.shp')

In [3]:
adm0 = gpd.read_file(admin0_file, encoding='utf-8-sig')
adm0_disputes = gpd.read_file(adm0_disputes_file, encoding='utf-8-sig')
adm1 = gpd.read_file(admin1_file, encoding='utf-8-sig')
adm2 = gpd.read_file(admin2_file, encoding='utf-8-sig')

c:\WBG\Anaconda3\envs\s2s_ingest\lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: C:\WBG\Work\data\ADMIN\NEW_WB_BOUNDS\WB_GAD_ADM0.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(
c:\WBG\Anaconda3\envs\s2s_ingest\lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: C:\WBG\Work\data\ADMIN\NEW_WB_BOUNDS\WB_GAD_ADM1.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(
c:\WBG\Anaconda3\envs\s2s_ingest\lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: C:\WBG\Work\data\ADMIN\NEW_WB_BOUNDS\WB_GAD_ADM2.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

In [4]:
# Add World Bank classifications to ADM0
wb_classes = get_wb_classifications_strict(grouping_version="38.0", region_version="2.0", income_version="2.0",)
wb_classes.rename({'ISO3':'ISO_A3', 'REGION':'WB_REGION', 'INCOME':'WB_INCOME'}, inplace=True, axis=1)
wb_classes['CONTINENT'] = wb_classes['CONTINENT'].fillna("001")
continent_names_map = {
    '002':'Africa',
    '005':'South America',
    '009':'Oceania',
    '142':'Asia',
    '150':'Europe',
    '001':'North America'
}
wb_classes['CONTINENT'] = wb_classes['CONTINENT'].map(continent_names_map)

adm0.drop("WB_REGION", axis=1, inplace=True)
adm0 = pd.merge(adm0, wb_classes, on='ISO_A3', how='left')
adm0.head()

,ISO_A3,ISO_A2,WB_A3,WB_STATUS,NAM_0,geometry,CONTINENT,WB_REGION,WB_INCOME
0,AUS,AU,AUS,Member State,Australia,"MULTIPOLYGON (((150.76958 -35.1223, 150.76522 ...",Oceania,EAS,HIC
1,BRN,BN,BRN,Member State,Brunei Darussalam,"MULTIPOLYGON (((114.86918 4.33475, 114.86713 4...",Asia,EAS,HIC
2,GUM,GU,GUM,Territory,Guam (U.S.),"MULTIPOLYGON (((144.82119 13.56665, 144.8213 1...",Oceania,EAS,HIC
3,IDN,ID,IDN,Member State,Indonesia,"MULTIPOLYGON (((113.48367 -6.8958, 113.48578 -...",Asia,EAS,UMC
4,JPN,JP,JPN,Member State,Japan,"MULTIPOLYGON (((137.25179 34.62394, 137.24687 ...",Asia,EAS,HIC

In [5]:
adm0['WB_REGION'].value_counts()

WB_REGION
ECS        64
LCN        42
EAS        38
AFE,SSF    26
MEA        23
AFW,SSF    22
SAS         6
NAC         3
Name: count, dtype: int64

In [6]:
# Ensure there are no empty country codes in ADM0
if adm0['ISO_A3'].isnull().sum() > 0:
    adm0.loc[adm0['ISO_A3'].isnull(),].to_file(os.path.join(out_folder, 'adm0_missing_iso_a3.gpkg'), driver='GPKG')

In [7]:
adm2.shape

(39655, 38)

## Combine ID columns

In [24]:
adm0.head()

,ISO_A3,ISO_A2,WB_A3,WB_STATUS,NAM_0,geometry,CONTINENT,WB_REGION,WB_INCOME
0,AUS,AU,AUS,Member State,Australia,"MULTIPOLYGON (((159.25479 -31.75707, 159.24725...",Oceania,EAS,HIC
1,BRN,BN,BRN,Member State,Brunei Darussalam,"MULTIPOLYGON (((115.27316 4.5534, 115.27277 4....",Asia,EAS,HIC
2,GUM,GU,GUM,Territory,Guam (U.S.),"MULTIPOLYGON (((144.82119 13.56665, 144.8213 1...",Oceania,EAS,HIC
3,IDN,ID,IDN,Member State,Indonesia,"MULTIPOLYGON (((131.67291 -1.35532, 131.66771 ...",Asia,EAS,UMC
4,JPN,JP,JPN,Member State,Japan,"MULTIPOLYGON (((153.98441 24.28068, 153.97994 ...",Asia,EAS,HIC

In [26]:
# Create unique ID column for ADM0, appending part numbers for countries with multiple parts
adm0['ADM0CD_c'] = ''

for iso3 in adm0['ISO_A3'].unique():
    sel_country = adm0.loc[adm0['ISO_A3'] == iso3,]
    if sel_country.shape[0] == 1:
        adm0.loc[adm0['ISO_A3'] == iso3, 'ADM0CD_c'] = f'{iso3}_01'
    else:
        sel_country = sel_country.sort_values('NAM_0')
        part_count = 1
        for idx, row in sel_country.iterrows():
            adm0.at[idx, 'ADM0CD_c'] = f'{iso3}_{part_count:02d}'
            part_count += 1

In [ ]:
adm1 = merge_id_columns(adm1, [['ADM1CD', 'ADM1CD_t']]) # ['P_CODE_1', 'P_CODE_1_t'], 
adm2 = merge_id_columns(adm2, [['ADM1CD', 'ADM1CD_t'], ['ADM2CD', 'ADM2CD_t']]) # ['P_CODE_1', 'P_CODE_1_t'], ['P_CODE_2', 'P_CODE_2_t'],

In [ ]:
# Check for duplicates in ADM1
test_col = 'ADM1CD_c'
adm1_dups = check_duplicates(adm1, test_col, os.path.join(out_folder, f'adm1_duplicates_{test_col}.gpkg'))

# Check for duplicates in ADM2
test_col = 'ADM2CD_c'
adm2_dups = check_duplicates(adm2, test_col, os.path.join(out_folder, f'adm2_duplicates_{test_col}.gpkg'))

ADM1CD_c duplicates: 22
ADM2CD_c duplicates: 5

In [10]:
# Check for data completeness in ADM0, AMD1, and ADM2
evaluate_data_completeness(adm0, list(adm0.columns), os.path.join(out_folder, 'adm0_data_completeness.log'))
evaluate_data_completeness(adm1, list(adm1.columns), os.path.join(out_folder, 'adm1_data_completeness.log'))
evaluate_data_completeness(adm2, ['ISO_A3', 'WB_STATUS', 'SOVEREIGN', 'NAM_0', 'NAM_1', 'ADM1CD_c', 'NAM_2', 'ADM2CD_c', 'WB_REGION'], os.path.join(out_folder, 'adm2_data_completeness.log'))

## Combine ADM0 with disputed territories

In [11]:
for col in adm0_disputes.columns:
    if not col in adm0.columns:
        adm0_disputes.drop(columns=[col], inplace=True)
adm0_disputes.head()
adm0_complete = pd.concat([adm0, adm0_disputes], ignore_index=True)
adm0_complete['geometry'] = adm0_complete['geometry'].buffer(0)

In [12]:
# Generate a global ocean mask from the admin divisions
ocean_polygon = box(-180, -90, 180, 90)  # Global bounding box for ocean
#clip ocean polygon to adm0 boundaries
ocean_polygon = ocean_polygon.difference(adm0_complete.union_all())  # Remove land areas
ocean_mask = gpd.GeoDataFrame([[1, ocean_polygon]], columns=['id', 'geometry'], crs=4326)

## Evaluate name duplication

In [13]:
# Evaluate duplicate names in adm1 and adm2
evaluate_duplicate_names(merged_adm1, 'NAM_1', 'ISO_A3', os.path.join(out_folder, "ADM1_name_duplicates.log"))
# Evaluate duplicate names in adm1 and adm2
evaluate_duplicate_names(merged_adm2, 'NAM_2', 'ADM1CD_c', os.path.join(out_folder, "ADM2_name_duplicates.log"))

In [14]:
# Use sjoin to identify overlapping polygons
''' NOT WORKING :(
sj = gpd.sjoin(adm0, adm0, how="inner", predicate="overlaps", lsuffix="left", rsuffix="right")
sj = sj[sj.index != sj.index_right]

sj['intersection_geom'] = sj['geometry_left'].intersection(sj['geometry_right'])
sj['intersection_area'] = sj['intersection_geom'].area
sj
'''

' NOT WORKING :(\nsj = gpd.sjoin(adm0, adm0, how="inner", predicate="overlaps", lsuffix="left", rsuffix="right")\nsj = sj[sj.index != sj.index_right]\n\nsj[\'intersection_geom\'] = sj[\'geometry_left\'].intersection(sj[\'geometry_right\'])\nsj[\'intersection_area\'] = sj[\'intersection_geom\'].area\nsj\n'

# Compare the new version to the previous version

In [15]:
old_admin0_file = "datacatalogfiles.worldbank.org/ddh-published/0038272/5/DR0095370/World Bank Official Boundaries (GeoPackage)/World Bank Official Boundaries - Admin 0_all_layers.gpkg"
old_adm0_disputes_file = "datacatalogfiles.worldbank.org/ddh-published/0038272/5/DR0095370/World Bank Official Boundaries (GeoPackage)/World Bank Official Boundaries - NDLSA.gpkg"
old_admin1_file = "datacatalogfiles.worldbank.org/ddh-published/0038272/5/DR0095370/World Bank Official Boundaries (GeoPackage)/World Bank Official Boundaries - Admin 1.gpkg"
old_admin2_file = "datacatalogfiles.worldbank.org/ddh-published/0038272/5/DR0095370/World Bank Official Boundaries (GeoPackage)/World Bank Official Boundaries - Admin 2.gpkg"

old_adm0 = gpd.read_file(f"https://{quote(old_admin0_file)}", encoding='utf-8-sig')
old_adm0_disputes = gpd.read_file(f"https://{quote(old_adm0_disputes_file)}", encoding='utf-8-sig')
old_adm1 = gpd.read_file(f"https://{quote(old_admin1_file)}", encoding='utf-8-sig')
old_adm2 = gpd.read_file(f"https://{quote(old_admin2_file)}", encoding='utf-8-sig')

In [16]:
# compare adm0
adm0['geometry'] = adm0['geometry'].buffer(0)
old_adm0['geometry'] = old_adm0['geometry'].buffer(0)
adm0_changes = compare_changes(old_adm0, adm0, 'NAM_0', ['NAM_0', 'ISO_A3'], 
                               os.path.join(out_folder, 'adm0_changes'))

# compare adm1
adm1['geometry'] = adm1['geometry'].buffer(0)
old_adm1['geometry'] = old_adm1['geometry'].buffer(0)
adm1_changes = compare_changes(old_adm1, adm1, 'ADM1CD_c', ['NAM_1', 'ISO_A3', 'ADM1CD_c'], 
                               os.path.join(out_folder, 'adm1_changes'))

# compare adm2
adm2['geometry'] = adm2['geometry'].buffer(0)
old_adm2['geometry'] = old_adm2['geometry'].buffer(0)
adm2_changes = compare_changes(old_adm2, adm2, 'ADM2CD_c', ['NAM_1', 'NAM_2', 'ISO_A3', 'ADM1CD_c', 'ADM2CD_c'], 
                               os.path.join(out_folder, 'adm2_changes'))

Changes in ISO_A3: 5
Changes in NAM_1: 26
Changes in NAM_1: 25
Changes in NAM_2: 65

## Separate datasets into primary and secondary tables

The delivered files contain several columns that are temporary or reference external sources. This section will separate the superfluous columns into a secondary table

In [17]:
adm1_primary = 'ADM1CD_c'
adm1_simple_cols = ['ISO_A3','ISO_A2','WB_A3','WB_REGION','WB_STATUS','NAM_0','NAM_1','ADM1CD_c','GEOM_SRCE', 'geometry']
adm1_bad_cols = [adm1_primary] + [x for x in merged_adm1.columns if x not in adm1_simple_cols]

adm2_primary = 'ADM2CD_c'
adm2_simple_cols = adm1_simple_cols + ['NAM_2','ADM2CD_c']
adm2_bad_cols = [adm2_primary] + [x for x in merged_adm2.columns if x not in adm2_simple_cols]

# Write out final versions in several data formats

write out:
- adm0 base
- adm0 NDLSA
- adm0 complete
- adm1 simple
- adm1 supplemntal columns
- adm2 simple 
- adm2 supplemental columns

in these formats
- geopackage
- geojson
- shapefile

In [23]:
for file_def in [
    (ocean_mask, 'WB_GAD_ocean_mask'),
    (adm0_complete, 'WB_GAD_ADM0_complete'),
    (adm0, 'WB_GAD_ADM0'),
    (adm0_disputes, 'WB_GAD_ADM0_NDLSA'),
    (merged_adm1.loc[:, adm1_simple_cols], 'WB_GAD_ADM1'),
    (merged_adm2.loc[:, adm2_simple_cols], 'WB_GAD_ADM2'),    
    ]:
    gdf, filename = file_def
    write_output(gdf, final_folder, filename)
    tPrint(f"completed {filename}")
# Save additional columns to CSV for reference
pd.DataFrame(merged_adm1.loc[:, adm1_bad_cols]).to_csv(os.path.join(final_folder, 'WB_GAD_adm1_additional_columns.csv'), index=False)
pd.DataFrame(merged_adm2.loc[:, adm2_bad_cols]).to_csv(os.path.join(final_folder, 'WB_GAD_adm2_additional_columns.csv'), index=False)

# Generate dissolved continents and regions
dissolve_folder = os.path.join(final_folder, 'REGIONS')
if not os.path.exists(dissolve_folder):
    os.makedirs(dissolve_folder)
for col in ['CONTINENT', 'WB_REGION']:
    if col in adm0_complete.columns:
        tPrint(f"Dissolving by {col}")
        dissolved = adm0_complete.dissolve(by=col, as_index=False)
        # project results to equal-area projection
        dissolved = dissolved.to_crs(epsg=8857)
        dissolved.to_file(os.path.join(dissolve_folder, f"WB_GAD_{col}.gpkg"), driver='GPKG')
tPrint("All output complete")

12:27:05	completed WB_GAD_ocean_mask
12:28:19	completed WB_GAD_ADM0_complete
12:29:35	completed WB_GAD_ADM0
12:29:36	completed WB_GAD_ADM0_NDLSA
12:31:30	completed WB_GAD_ADM1
12:35:16	completed WB_GAD_ADM2
12:35:16	Dissolving by CONTINENT
12:36:16	Dissolving by WB_REGION
12:37:12	All output complete